Revert "../drivers/misc/mediatek/task_turbo/task_turbo.c:59:6: error: no member named 'cpu_prefer' in 'struct task_struct'"
This reverts commit a9e3da43eed0c30209bd0239d876cb43d095eb00.